export const airports = [
   // ===== AFRICA =====
   { code: "MPM", name: "Maputo, Mozambique" },
   { code: "BEW", name: "Beira, Mozambique" },
   { code: "VPY", name: "Vilankulo, Mozambique" },
   { code: "TET", name: "Tete, Mozambique" },
   { code: "APL", name: "Nampula, Mozambique" },
   { code: "POL", name: "Pemba, Mozambique" },

   { code: "LAD", name: "Luanda, Angola" },
   { code: "CBT", name: "Catumbela, Angola" },
   { code: "SDD", name: "Lubango, Angola" },

   { code: "JNB", name: "Johannesburg, South Africa" },
   { code: "DUR", name: "Durban, South Africa" },
   { code: "PLZ", name: "Gqeberha (Port Elizabeth), South Africa" },
   { code: "BFN", name: "Bloemfontein, South Africa" },

   { code: "HRE", name: "Harare, Zimbabwe" },
   { code: "VFA", name: "Victoria Falls, Zimbabwe" },

   { code: "LUN", name: "Lusaka, Zambia" },
   { code: "NLA", name: "Ndola, Zambia" },

   { code: "DAR", name: "Dar es Salaam, Tanzania" },
   { code: "ZNZ", name: "Zanzibar, Tanzania" },
   { code: "JRO", name: "Kilimanjaro, Tanzania" },

   { code: "EBB", name: "Entebbe, Uganda" },
   { code: "KGL", name: "Kigali, Rwanda" },
   { code: "BJM", name: "Bujumbura, Burundi" },

   { code: "LOS", name: "Lagos, Nigeria" },
   { code: "ABV", name: "Abuja, Nigeria" },
   { code: "PHC", name: "Port Harcourt, Nigeria" },
   { code: "ENU", name: "Enugu, Nigeria" },

   { code: "ACC", name: "Accra, Ghana" },
   { code: "KMS", name: "Kumasi, Ghana" },

   { code: "DKR", name: "Dakar, Senegal" },
   { code: "ROB", name: "Monrovia, Liberia" },
   { code: "FNA", name: "Freetown, Sierra Leone" },

   { code: "ADD", name: "Addis Ababa, Ethiopia" },
   { code: "JIB", name: "Djibouti City, Djibouti" },
   { code: "ASM", name: "Asmara, Eritrea" },

   { code: "CAI", name: "Cairo, Egypt" },
   { code: "HRG", name: "Hurghada, Egypt" },

   { code: "CMN", name: "Casablanca, Morocco" },
   { code: "RAK", name: "Marrakesh, Morocco" },
   { code: "TUN", name: "Tunis, Tunisia" },

   // ===== ASIA =====
   { code: "DEL", name: "New Delhi, India" },
   { code: "BOM", name: "Mumbai, India" },
   { code: "BLR", name: "Bangalore, India" },
   { code: "MAA", name: "Chennai, India" },

   { code: "DAC", name: "Dhaka, Bangladesh" },
   { code: "CMB", name: "Colombo, Sri Lanka" },
   { code: "KTM", name: "Kathmandu, Nepal" },

   { code: "ISB", name: "Islamabad, Pakistan" },
   { code: "LHE", name: "Lahore, Pakistan" },
   { code: "KHI", name: "Karachi, Pakistan" },

   { code: "HAN", name: "Hanoi, Vietnam" },
   { code: "SGN", name: "Ho Chi Minh City, Vietnam" },

   { code: "PNH", name: "Phnom Penh, Cambodia" },
   { code: "VTE", name: "Vientiane, Laos" },
   { code: "RGN", name: "Yangon, Myanmar" },

   { code: "MNL", name: "Manila, Philippines" },
   { code: "CEB", name: "Cebu, Philippines" },

   { code: "CGK", name: "Jakarta, Indonesia" },
   { code: "DPS", name: "Bali (Denpasar), Indonesia" },

   // ===== LATIN AMERICA =====
   { code: "UIO", name: "Quito, Ecuador" },
   { code: "GYE", name: "Guayaquil, Ecuador" },

   { code: "LPB", name: "La Paz, Bolivia" },
   { code: "VVI", name: "Santa Cruz, Bolivia" },

   { code: "ASU", name: "Asunción, Paraguay" },
   { code: "MVD", name: "Montevideo, Uruguay" },

   { code: "HAV", name: "Havana, Cuba" },
   { code: "SJO", name: "San José, Costa Rica" },
   { code: "SAL", name: "San Salvador, El Salvador" },
   { code: "GUA", name: "Guatemala City, Guatemala" },
   { code: "TGU", name: "Tegucigalpa, Honduras" },
   { code: "MGA", name: "Managua, Nicaragua" },

   // ===== EUROPE (secondary cities) =====
   { code: "OPO", name: "Porto, Portugal" },
   { code: "FAO", name: "Faro, Portugal" },

   { code: "BCN", name: "Barcelona, Spain" },
   { code: "SVQ", name: "Seville, Spain" },

   { code: "LYS", name: "Lyon, France" },
   { code: "MRS", name: "Marseille, France" },

   { code: "NAP", name: "Naples, Italy" },
   { code: "MXP", name: "Milan Malpensa, Italy" },

   { code: "PRG", name: "Prague, Czech Republic" },
   { code: "BUD", name: "Budapest, Hungary" },
   { code: "OTP", name: "Bucharest, Romania" },
   { code: "SOF", name: "Sofia, Bulgaria" },
   { code: "ATH", name: "Athens, Greece" },
   { code: "DUB", name: "Dublin, Ireland" },
   { code: "EDI", name: "Edinburgh, United Kingdom" },
   { code: "LIS", name: "Lisbon, Portugal" },
   { code: "MAD", name: "Madrid, Spain" },
   { code: "PAR", name: "Paris, France" },
   { code: "LON", name: "London, United Kingdom" },
   { code: "FRA", name: "Frankfurt, Germany" },
   { code: "AMS", name: "Amsterdam, Netherlands" },
   { code: "ROM", name: "Rome, Italy" },
   { code: "BER", name: "Berlin, Germany" },
   { code: "DUB", name: "Dublin, Ireland" },
   { code: "NYC", name: "New York, USA" },
   { code: "LAX", name: "Los Angeles, USA" },
   { code: "DXB", name: "Dubai, UAE" },
   { code: "IST", name: "Istanbul, Turkey" },
   { code: "SIN", name: "Singapore, Singapore" },
   { code: "BKK", name: "Bangkok, Thailand" },
   { code: "SYD", name: "Sydney, Australia" },
   { code: "GRU", name: "São Paulo, Brazil" },
   { code: "EZE", name: "Buenos Aires, Argentina" },
   { code: "CPT", name: "Cape Town, South Africa" },
   { code: "NBO", name: "Nairobi, Kenya" },
   { code: "MCO", name: "Orlando, USA" },
   { code: "MIA", name: "Miami, USA" },
   { code: "MEX", name: "Mexico City, Mexico" },
   { code: "LIM", name: "Lima, Peru" },
   { code: "BOG", name: "Bogotá, Colombia" },
   { code: "SCL", name: "Santiago, Chile" },
   { code: "PTY", name: "Panama City, Panama" },
   { code: "SAN", name: "San Diego, USA" },
   { code: "SFO", name: "San Francisco, USA" },
   { code: "SEA", name: "Seattle, USA" },
   { code: "DEN", name: "Denver, USA" },
   { code: "ORD", name: "Chicago, USA" },
   { code: "DFW", name: "Dallas, USA" },
   { code: "HOU", name: "Houston, USA" },
   { code: "ATL", name: "Atlanta, USA" },
   { code: "BOS", name: "Boston, USA" },
   { code: "WAS", name: "Washington, D.C., USA" },
   { code: "PHL", name: "Philadelphia, USA" },
   { code: "CLT", name: "Charlotte, USA" },
   { code: "DTW", name: "Detroit, USA" },
   { code: "MSP", name: "Minneapolis, USA" },
   { code: "SLC", name: "Salt Lake City, USA" },
   { code: "PHX", name: "Phoenix, USA" },
   { code: "LAS", name: "Las Vegas, USA" },
   { code: "PDX", name: "Portland, USA" },
   { code: "IND", name: "Indianapolis, USA" },
   { code: "STL", name: "St. Louis, USA" }, 
   { code: "MCI", name: "Kansas City, USA" },  
   { code: "MDW", name: "Chicago Midway, USA" }, 
   { code: "BNA", name: "Nashville, USA" }, 
   { code: "RDU", name: "Raleigh/Durham, USA" }, 
   { code: "AUS", name: "Austin, USA" }, 
   { code: "SAT", name: "San Antonio, USA" }, 
   { code: "SNA", name: "Santa Ana, USA" }, 
   { code: "OAK", name: "Oakland, USA" }, 
   { code: "SJC", name: "San Jose, USA" }, 
   { code: "SMF", name: "Sacramento, USA" }, 
   { code: "SBA", name: "Santa Barbara, USA" }, 
   { code: "FAT", name: "Fresno, USA" }, 
   { code: "RNO", name: "Reno, USA" }, 
   { code: "BOI", name: "Boise, USA" }, 
   { code: "GEG", name: "Spokane, USA" }, 
   { code: "COS", name: "Colorado Springs, USA" }, 
   { code: "ABQ", name: "Albuquerque, USA" }, 
   { code: "ELP", name: "El Paso, USA" }, 
   { code: "TUS", name: "Tucson, USA" }, 
   { code: "OKC", name: "Oklahoma City, USA" }, 
   { code: "OMA", name: "Omaha, USA" }, 
   { code: "DSM", name: "Des Moines, USA" }, 
   { code: "MKE", name: "Milwaukee, USA" }, 
   { code: "GRR", name: "Grand Rapids, USA" }, 
   { code: "CLE", name: "Cleveland, USA" }, 
   { code: "CMH", name: "Columbus, USA" }, 
   { code: "PIT", name: "Pittsburgh, USA" }, 
   { code: "BUF", name: "Buffalo, USA" }, 
   { code: "ROC", name: "Rochester, USA" }, 
   { code: "SYR", name: "Syracuse, USA" }, 
   { code: "ALB", name: "Albany, USA" }, 
   { code: "BDL", name: "Hartford, USA" }, 
   { code: "PVD", name: "Providence, USA" }, 
   { code: "PWM", name: "Portland, USA" }, 
   { code: "MHT", name: "Manchester, USA" }, 
   { code: "BGR", name: "Bangor, USA" }, 
   { code: "BTV", name: "Burlington, USA" },
];
