export const airports = [
    { code: "LIS", name: "Lisbon, Portugal" },
    { code: "MAD", name: "Madrid, Spain" },
    { code: "PAR", name: "Paris, France" },
    { code: "LON", name: "London, United Kingdom" },
    { code: "FRA", name: "Frankfurt, Germany" },
    { code: "AMS", name: "Amsterdam, Netherlands" },
    { code: "ROM", name: "Rome, Italy" },
    { code: "BER", name: "Berlin, Germany" },
    { code: "DUB", name: "Dublin, Ireland" },
    { code: "NYC", name: "New York, USA" },
    { code: "LAX", name: "Los Angeles, USA" },
    { code: "DXB", name: "Dubai, UAE" },
    { code: "IST", name: "Istanbul, Turkey" },
    { code: "SIN", name: "Singapore, Singapore" },
    { code: "BKK", name: "Bangkok, Thailand" },
    { code: "SYD", name: "Sydney, Australia" },
    { code: "GRU", name: "São Paulo, Brazil" },
    { code: "EZE", name: "Buenos Aires, Argentina" },
    { code: "CPT", name: "Cape Town, South Africa" },
    { code: "NBO", name: "Nairobi, Kenya" },
    { code: "MCO", name: "Orlando, USA" },
    { code: "MIA", name: "Miami, USA" },
    { code: "MEX", name: "Mexico City, Mexico" },
    { code: "LIM", name: "Lima, Peru" },
    { code: "BOG", name: "Bogotá, Colombia" },
    { code: "SCL", name: "Santiago, Chile" },
    { code: "PTY", name: "Panama City, Panama" },
    { code: "SAN", name: "San Diego, USA" },
    { code: "SFO", name: "San Francisco, USA" },
    { code: "SEA", name: "Seattle, USA" },
    { code: "DEN", name: "Denver, USA" },
    { code: "ORD", name: "Chicago, USA" },
    { code: "DFW", name: "Dallas, USA" },
    { code: "HOU", name: "Houston, USA" },
    { code: "ATL", name: "Atlanta, USA" },
    { code: "BOS", name: "Boston, USA" },
    { code: "WAS", name: "Washington, D.C., USA" },
    { code: "PHL", name: "Philadelphia, USA" },
    { code: "CLT", name: "Charlotte, USA" },
    { code: "DTW", name: "Detroit, USA" },
    { code: "MSP", name: "Minneapolis, USA" },
    { code: "SLC", name: "Salt Lake City, USA" },
    { code: "PHX", name: "Phoenix, USA" },
    { code: "LAS", name: "Las Vegas, USA" },
    { code: "PDX", name: "Portland, USA" },
    { code: "IND", name: "Indianapolis, USA" },
    { code: "STL", name: "St. Louis, USA" },
    { code: "MCI", name: "Kansas City, USA" },
    { code: "MDW", name: "Chicago Midway, USA" },
    { code: "BNA", name: "Nashville, USA" },
    { code: "RDU", name: "Raleigh/Durham, USA" },
    { code: "AUS", name: "Austin, USA" },
    { code: "SAT", name: "San Antonio, USA" },
    { code: "SNA", name: "Santa Ana, USA" },
    { code: "OAK", name: "Oakland, USA" },
    { code: "SJC", name: "San Jose, USA" },
    { code: "SMF", name: "Sacramento, USA" },
    { code: "SBA", name: "Santa Barbara, USA" },
    { code: "FAT", name: "Fresno, USA" },
    { code: "RNO", name: "Reno, USA" },
    { code: "BOI", name: "Boise, USA" },
    { code: "GEG", name: "Spokane, USA" },
    { code: "COS", name: "Colorado Springs, USA" },
    { code: "ABQ", name: "Albuquerque, USA" },
    { code: "ELP", name: "El Paso, USA" },
    { code: "TUS", name: "Tucson, USA" },
    { code: "OKC", name: "Oklahoma City, USA" },
    { code: "OMA", name: "Omaha, USA" },
    { code: "DSM", name: "Des Moines, USA" },
    { code: "MKE", name: "Milwaukee, USA" },
    { code: "GRR", name: "Grand Rapids, USA" },
    { code: "CLE", name: "Cleveland, USA" },
    { code: "CMH", name: "Columbus, USA" },
    { code: "PIT", name: "Pittsburgh, USA" },
    { code: "BUF", name: "Buffalo, USA" },
    { code: "ROC", name: "Rochester, USA" },
    { code: "SYR", name: "Syracuse, USA" },
    { code: "ALB", name: "Albany, USA" },
    { code: "BDL", name: "Hartford, USA" },
    { code: "PVD", name: "Providence, USA" },
    { code: "PWM", name: "Portland, USA" },
    { code: "MHT", name: "Manchester, USA" },
    { code: "BGR", name: "Bangor, USA" },
    { code: "BTV", name: "Burlington, USA" },
];
